#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

[ -f .env ] || { echo "error: .env missing — run ./setup.sh first" >&2; exit 2; }
# A graphical login may move from :0 to :1 after a reboot or display-manager
# restart.  The caller's live DISPLAY must win over the setup-time .env value.
CALLER_DISPLAY="${DISPLAY:-}"
set -a
# shellcheck source=/dev/null # .env is generated by ./setup.sh.
source .env
set +a
if [ -n "$CALLER_DISPLAY" ]; then
  DISPLAY="$CALLER_DISPLAY"
  export DISPLAY
fi

DC() { docker compose --env-file .env "$@"; }

require_x11_display() {
  local number="${DISPLAY#:}"
  number="${number%%.*}"
  if [[ "$DISPLAY" =~ ^:[0-9]+(\.[0-9]+)?$ ]] && [ -S "/tmp/.X11-unix/X$number" ]; then
    return
  fi

  local -a sockets=(/tmp/.X11-unix/X*)
  if [ "${#sockets[@]}" -eq 1 ] && [ -S "${sockets[0]}" ]; then
    DISPLAY=":${sockets[0]##*/X}"
    export DISPLAY
    echo "[x11] configured display is unavailable; using active $DISPLAY" >&2
    return
  fi

  echo "error: X11 display $DISPLAY is unavailable; expected /tmp/.X11-unix/X$number" >&2
  echo "active sockets: ${sockets[*]:-none}" >&2
  exit 2
}

up_once() {
  if ! docker compose --env-file .env ps -q dev >/dev/null 2>&1; then
    DC up -d dev
  else
    state=$(docker inspect -f '{{.State.Running}}' "${COMPOSE_PROJECT_NAME:-humanoid-lab}-dev" 2>/dev/null || echo false)
    [ "$state" = "true" ] || DC up -d dev
  fi
}

shell_env() { # $1 = use-... function name
  up_once
  DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && $1 && exec bash"
}

cleanup_isaac_demo() { # $1 = container-side pidfile
  # docker compose exec does not terminate its container process when this
  # client is interrupted. The pidfile is per invocation, so cleanup cannot
  # affect another demo or an interactive development shell.
  local pidfile="$1"
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  DC exec -T dev bash -lc '
    pidfile=$1
    [ -r "$pidfile" ] || exit 0
    read -r pid <"$pidfile" || exit 0
    case "$pid" in (*[!0-9]*|"") rm -f -- "$pidfile"; exit 0;; esac
    if [ -r "/proc/$pid/cmdline" ] &&
       tr "\\0" " " <"/proc/$pid/cmdline" | grep -Fq "/opt/src/isaaclab/scripts/demos/"; then
      # The demo starts in its own session, so this also stops subprocesses
      # started by Isaac Sim rather than leaving an orphaned Kit process.
      kill -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
    fi
    rm -f -- "$pidfile"
  ' -- "$pidfile" >/dev/null 2>&1 || true
}

isaac_demo() {
  local demo="$1"
  local arg
  local pidfile
  local exec_pid
  local rc
  local add_headless=1
  local direct_gui=0
  local -a demo_args=()
  shift
  [[ "$demo" =~ ^[A-Za-z0-9_-]+\.py$ ]] || {
    echo "error: demo must be a filename from /opt/src/isaaclab/scripts/demos (for example: quadrupeds.py)" >&2
    exit 2
  }
  # NVIDIA supports Python apps in the Isaac Sim container in headless mode.
  # A livestream explicitly selects the corresponding headless Kit experience.
  for arg in "$@"; do
    case "$arg" in
      --gui)
        direct_gui=1
        ;;
      --headless|--livestream|--livestream=*)
        add_headless=0
        demo_args+=("$arg")
        ;;
      *) demo_args+=("$arg") ;;
    esac
  done
  if [ "$direct_gui" -eq 1 ] && [ "$add_headless" -eq 0 ]; then
    echo "error: --gui cannot be combined with --headless or --livestream" >&2
    exit 2
  fi
  [ "$direct_gui" -eq 0 ] || require_x11_display
  if [ "$add_headless" -eq 1 ]; then
    if [ "$direct_gui" -eq 1 ]; then
      echo "[isaac-demo] experimental direct X11 GUI mode" >&2
    else
      echo "[isaac-demo] container mode: adding --headless (use --gui for experimental local X11, or --livestream 1 or 2 for remote viewing)" >&2
      demo_args+=(--headless)
    fi
  fi
  up_once
  pidfile="/tmp/humanoid-lab-isaac-demo-$$-$RANDOM.pid"
  on_isaac_demo_signal() {
    # wait(1) is interruptible; unlike a foreground compose exec, this lets
    # the host shell actually run cleanup when timeout or SSH signals it.
    cleanup_isaac_demo "$pidfile"
    if [ -n "${exec_pid:-}" ]; then
      kill "$exec_pid" 2>/dev/null || true
      wait "$exec_pid" 2>/dev/null || true
    fi
    exit 143
  }
  trap on_isaac_demo_signal INT TERM HUP
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  DC exec -e DISPLAY="$DISPLAY" dev bash -lc '
    source /opt/humanoid-lab/entrypoint.sh
    use-isaac-sonic
    # Keep Kit extension discovery scoped to Isaac Lab rather than the repo.
    cd /opt/src/isaaclab
    pidfile=$1
    demo=$2
    shift 2
    rm -f -- "$pidfile"
    setsid python "/opt/src/isaaclab/scripts/demos/$demo" "$@" &
    demo_pid=$!
    printf "%s\n" "$demo_pid" >"$pidfile"
    cleanup_demo() {
      kill -- "-$demo_pid" 2>/dev/null || kill "$demo_pid" 2>/dev/null || true
      rm -f -- "$pidfile"
    }
    # A lost compose-exec client sends HUP to this shell, not to the setsid demo.
    trap "cleanup_demo; exit 143" INT TERM HUP
    if wait "$demo_pid"; then
      rc=0
    else
      rc=$?
    fi
    trap - INT TERM HUP
    rm -f -- "$pidfile"
    exit "$rc"
  ' -- "$pidfile" "$demo" "${demo_args[@]}" &
  exec_pid=$!
  if wait "$exec_pid"; then
    rc=0
  else
    rc=$?
  fi
  trap - INT TERM HUP
  cleanup_isaac_demo "$pidfile"
  return "$rc"
}

case "${1:-}" in
  "")
    up_once
    DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && exec bash"
    ;;
  isaac)      shell_env use-isaac-sonic ;;
  isaac-demo)
    [ "$#" -ge 2 ] || { echo "usage: $0 isaac-demo <demo.py> [--gui|--headless|--livestream 1|2] [Isaac Lab args]" >&2; exit 2; }
    isaac_demo "$2" "${@:3}"
    ;;
  isaac-stream)
    [ "$#" -ge 2 ] || { echo "usage: $0 isaac-stream <demo.py> [Isaac Lab args]" >&2; exit 2; }
    echo "error: Isaac Sim 5.1 WebRTC streaming is disabled on this host." >&2
    echo "The official no-window streaming app crashes in librtx.scenedb.plugin.so before it opens a stable endpoint." >&2
    echo "Use ./dev.sh isaac-demo $2 for headless simulation until the Isaac Sim/driver compatibility decision is applied." >&2
    exit 1
    ;;
  webrtc-client)
    client_path="${ISAAC_WEBRTC_CLIENT:-$HOME/Applications/IsaacSim/isaacsim-webrtc-streaming-client-1.1.5-linux-x64.AppImage}"
    [ -x "$client_path" ] || {
      echo "error: WebRTC client missing: $client_path" >&2
      echo "run: ./scripts/install-isaac-webrtc-client.sh" >&2
      exit 2
    }
    exec "$client_path"
    ;;
  sonic-sim)  shell_env use-sonic-sim ;;
  groot)      shell_env use-groot ;;
  isaac-g1)
    profile="${2:-}"
    case "$profile" in
      no_hands) profile_file=configs/profiles/isaac-g1-no_hands.json ;;
      inspire-ftp) profile_file=configs/profiles/isaac-g1-inspire-ftp.json ;;
      dex3) profile_file=configs/profiles/isaac-g1-dex3.json ;;
      *) echo "usage: $0 isaac-g1 {no_hands|inspire-ftp|dex3} [--test passive-fall] [--headless] [--duration SECONDS]" >&2; exit 2 ;;
    esac
    headless=0
    for arg in "${@:3}"; do
      [ "$arg" != "--headless" ] || headless=1
    done
    [ "$headless" -eq 1 ] || require_x11_display
    up_once
    # shellcheck disable=SC2016 # Positional parameters expand inside the container shell.
    DC exec -e DISPLAY="$DISPLAY" dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && exec python scripts/run-isaac-g1.py --profile "$1" "${@:2}"' isaac-g1 "$profile_file" "${@:3}"
    ;;
  doctor)
    ./doctor.sh
    ;;
  smoke)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && /opt/humanoid-lab/smoke-test.sh'
    ;;
  groot-finetune-smoke)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-groot && exec /opt/humanoid-lab/groot-finetune-smoke.sh "$@"' groot-finetune-smoke "${@:2}"
    ;;
  sync)
    up_once
    DC exec -T dev /opt/humanoid-lab/bootstrap-venvs.sh
    ;;
  fetch-models)
    up_once
    DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && scripts/fetch-models.sh"
    ;;
  fetch-groot-demo-data)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-groot && exec /opt/humanoid-lab/fetch-groot-demo-data.sh "$@"' fetch-groot-demo-data "${@:2}"
    ;;
  hf-login)
    up_once
    DC exec dev bash -lc '
      source /opt/humanoid-lab/entrypoint.sh && use-groot
      if hf auth login --help >/dev/null 2>&1; then exec hf auth login; fi
      if hf login --help >/dev/null 2>&1; then exec hf login; fi
      exec huggingface-cli login'
    ;;
  stop)
    DC stop
    ;;
  rebuild)
    docker compose --env-file .env --progress=plain build dev
    DC up -d --force-recreate dev
    ;;
  foxy)
    echo "error: foxy profile not enabled" >&2
    exit 2
    ;;
  *)
    echo "usage: $0 [isaac|isaac-demo|isaac-stream|webrtc-client|sonic-sim|groot|isaac-g1 {no_hands|inspire-ftp|dex3}|doctor|smoke|groot-finetune-smoke|sync|fetch-models|fetch-groot-demo-data|hf-login|stop|rebuild|foxy]" >&2
    exit 2
    ;;
esac
