#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

[ -f .env ] || { echo "error: .env missing — run ./setup.sh first" >&2; exit 2; }
# A graphical login may move from :0 to :1 after a reboot or display-manager
# restart.  The caller's live DISPLAY must win over the setup-time .env value.
CALLER_DISPLAY="${DISPLAY:-}"
set -a
# shellcheck source=/dev/null # .env is generated by ./setup.sh.
source .env
set +a
if [ -n "$CALLER_DISPLAY" ]; then
  DISPLAY="$CALLER_DISPLAY"
  export DISPLAY
fi

DC() { docker compose --env-file .env "$@"; }

# Filled by livestream_settings() when a command streams its UI instead of
# opening a window on the host's physical screen.
LIVESTREAM_ARGS=()
LIVESTREAM_ENV=()

require_x11_display() {
  local number="${DISPLAY#:}"
  number="${number%%.*}"
  if [[ "$DISPLAY" =~ ^:[0-9]+(\.[0-9]+)?$ ]] && [ -S "/tmp/.X11-unix/X$number" ]; then
    return
  fi

  local -a sockets=(/tmp/.X11-unix/X*)
  if [ "${#sockets[@]}" -eq 1 ] && [ -S "${sockets[0]}" ]; then
    DISPLAY=":${sockets[0]##*/X}"
    export DISPLAY
    echo "[x11] configured display is unavailable; using active $DISPLAY" >&2
    return
  fi

  echo "error: X11 display $DISPLAY is unavailable; expected /tmp/.X11-unix/X$number" >&2
  echo "active sockets: ${sockets[*]:-none}" >&2
  exit 2
}

# Interactive Isaac runs are WebRTC servers: the application has no local window
# and its full UI is streamed, so nothing appears on the host's physical screen.
# ISAAC_LIVESTREAM_ENDPOINT overrides the advertised address; the default is the
# host's Tailscale IPv4, which is what remote clients reach.
livestream_settings() {
  local endpoint="${ISAAC_LIVESTREAM_ENDPOINT:-}"
  if [ -z "$endpoint" ] && command -v tailscale >/dev/null 2>&1; then
    endpoint="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
  fi
  ISAAC_LIVESTREAM_ENDPOINT="$endpoint"
  LIVESTREAM_ARGS=()
  LIVESTREAM_ENV=()
  if [ -n "$endpoint" ]; then
    LIVESTREAM_ARGS=(--livestream 1)
    LIVESTREAM_ENV=(-e "PUBLIC_IP=$endpoint")
  else
    LIVESTREAM_ARGS=(--livestream 2)
  fi
}

livestream_banner() { # $1 = command label
  echo "[$1] WebRTC livestream, no local window: connect the Isaac Sim WebRTC client to" >&2
  echo "[$1] ${ISAAC_LIVESTREAM_ENDPOINT:-this host}, port ${ISAAC_LIVESTREAM_PORT:-49100}" >&2
}

# Shared mode selection for the isaac-g1 entries: the default streams over
# WebRTC, --gui keeps the direct X11 window, --headless runs with no UI at all.
g1_mode_args() { # $1 = label; remaining arguments are the caller's flags
  local label="$1"
  local headless=0
  local arg
  shift
  G1_GUI=0
  for arg in "$@"; do
    case "$arg" in
      --gui) G1_GUI=1 ;;
      --headless) headless=1 ;;
    esac
  done
  if [ "$G1_GUI" -eq 1 ] && [ "$headless" -eq 1 ]; then
    echo "error: --gui cannot be combined with --headless" >&2
    exit 2
  fi
  G1_ARGS=()
  if [ "$G1_GUI" -eq 1 ]; then
    require_x11_display
  elif [ "$headless" -eq 0 ]; then
    livestream_settings
    G1_ARGS=("${LIVESTREAM_ARGS[@]}")
    livestream_banner "$label"
  fi
}

up_once() {
  if ! docker compose --env-file .env ps -q dev >/dev/null 2>&1; then
    DC up -d dev
  else
    state=$(docker inspect -f '{{.State.Running}}' "${COMPOSE_PROJECT_NAME:-humanoid-lab}-dev" 2>/dev/null || echo false)
    [ "$state" = "true" ] || DC up -d dev
  fi
}

shell_env() { # $1 = use-... function name
  up_once
  DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && $1 && exec bash"
}

cleanup_isaac_demo() { # $1 = container-side pidfile
  # docker compose exec does not terminate its container process when this
  # client is interrupted. The pidfile is per invocation, so cleanup cannot
  # affect another demo or an interactive development shell.
  local pidfile="$1"
  local container_id
  container_id="$(DC ps -q dev 2>/dev/null)" || return 0
  [ -n "$container_id" ] || return 0
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  docker exec "$container_id" bash -lc '
    pidfile=$1
    [ -r "$pidfile" ] || exit 0
    read -r pid <"$pidfile" || exit 0
    case "$pid" in (*[!0-9]*|"") rm -f -- "$pidfile"; exit 0;; esac
    if [ -r "/proc/$pid/cmdline" ] &&
       tr "\\0" " " <"/proc/$pid/cmdline" | grep -Fq "/opt/src/isaaclab/scripts/demos/"; then
      # The demo starts in its own session, so this also stops subprocesses
      # started by Isaac Sim rather than leaving an orphaned Kit process.
      kill -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
      for _ in {1..20}; do
        [ ! -d "/proc/$pid" ] && break
        sleep 0.1
      done
      [ ! -d "/proc/$pid" ] || kill -KILL -- "-$pid" 2>/dev/null || true
    fi
    rm -f -- "$pidfile"
  ' -- "$pidfile" >/dev/null 2>&1 || true
}

isaac_demo() {
  local demo="$1"
  local arg
  local pidfile
  local exec_pid
  local rc
  local add_headless=1
  local direct_gui=0
  local -a demo_args=()
  shift
  [[ "$demo" =~ ^[A-Za-z0-9_-]+\.py$ ]] || {
    echo "error: demo must be a filename from /opt/src/isaaclab/scripts/demos (for example: quadrupeds.py)" >&2
    exit 2
  }
  # NVIDIA supports Python apps in the Isaac Sim container in headless mode.
  # A livestream explicitly selects the corresponding headless Kit experience.
  for arg in "$@"; do
    case "$arg" in
      --gui)
        direct_gui=1
        ;;
      --headless|--livestream|--livestream=*)
        add_headless=0
        demo_args+=("$arg")
        ;;
      *) demo_args+=("$arg") ;;
    esac
  done
  if [ "$direct_gui" -eq 1 ] && [ "$add_headless" -eq 0 ]; then
    echo "error: --gui cannot be combined with --headless or --livestream" >&2
    exit 2
  fi
  [ "$direct_gui" -eq 0 ] || require_x11_display
  if [ "$add_headless" -eq 1 ]; then
    if [ "$direct_gui" -eq 1 ]; then
      echo "[isaac-demo] experimental direct X11 GUI mode" >&2
    else
      livestream_settings
      livestream_banner isaac-demo
      demo_args+=("${LIVESTREAM_ARGS[@]}")
    fi
  fi
  up_once
  pidfile="/tmp/humanoid-lab-isaac-demo-$$-$RANDOM.pid"
  on_isaac_demo_signal() {
    # wait(1) is interruptible; unlike a foreground compose exec, this lets
    # the host shell actually run cleanup when timeout or SSH signals it.
    cleanup_isaac_demo "$pidfile"
    if [ -n "${exec_pid:-}" ]; then
      kill "$exec_pid" 2>/dev/null || true
      wait "$exec_pid" 2>/dev/null || true
    fi
    exit 143
  }
  trap on_isaac_demo_signal INT TERM HUP
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  DC exec -T -e DISPLAY="$DISPLAY" "${LIVESTREAM_ENV[@]}" dev bash -lc '
    source /opt/humanoid-lab/entrypoint.sh
    use-isaac-sonic
    # Keep Kit extension discovery scoped to Isaac Lab rather than the repo.
    cd /opt/src/isaaclab
    pidfile=$1
    demo=$2
    shift 2
    rm -f -- "$pidfile" "${pidfile}.status"
    setsid python "/opt/src/isaaclab/scripts/demos/$demo" "$@" &
    demo_pid=$!
    printf "%s\n" "$demo_pid" >"$pidfile"
    cleanup_demo() {
      kill -- "-$demo_pid" 2>/dev/null || kill "$demo_pid" 2>/dev/null || true
      rm -f -- "$pidfile"
    }
    # A lost compose-exec client sends HUP to this shell, not to the setsid demo.
    trap "cleanup_demo; exit 143" INT TERM HUP
    if wait "$demo_pid"; then
      rc=0
    else
      rc=$?
    fi
    trap - INT TERM HUP
    rm -f -- "$pidfile"
    exit "$rc"
  ' -- "$pidfile" "$demo" "${demo_args[@]}" &
  exec_pid=$!
  if wait "$exec_pid"; then
    rc=0
  else
    rc=$?
  fi
  trap - INT TERM HUP
  cleanup_isaac_demo "$pidfile"
  return "$rc"
}

cleanup_isaac_g1() { # $1 = container-side pidfile
  local pidfile="$1"
  local container_id
  container_id="$(DC ps -q dev 2>/dev/null)" || return 0
  [ -n "$container_id" ] || return 0
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  docker exec "$container_id" bash -lc '
    pidfile=$1
    [ -r "$pidfile" ] || exit 0
    read -r pid <"$pidfile" || exit 0
    case "$pid" in (*[!0-9]*|"") rm -f -- "$pidfile"; exit 0;; esac
    if [ -r "/proc/$pid/cmdline" ] &&
       tr "\\0" " " <"/proc/$pid/cmdline" | grep -Fq "scripts/run-isaac-g1.py"; then
      kill -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
      # Do not let a disconnected compose-exec client leave Kit behind.
      for _ in {1..20}; do
        [ ! -d "/proc/$pid" ] && break
        sleep 0.1
      done
      [ ! -d "/proc/$pid" ] || kill -KILL -- "-$pid" 2>/dev/null || true
    fi
    rm -f -- "$pidfile" "${pidfile}.status"
  ' -- "$pidfile" >/dev/null 2>&1 || true
}

run_isaac_g1() { # $1 = profile path; remaining args belong to the runner
  local profile_file="$1"
  local pidfile="/tmp/humanoid-lab-isaac-g1-$$-$RANDOM.pid"
  local statusfile="${pidfile}.status"
  local container_id
  local exec_pid=""
  local recorded_rc=""
  local rc
  shift

  container_id="$(DC ps -q dev)"
  [ -n "$container_id" ] || { echo "error: dev container is not running" >&2; return 2; }

  on_isaac_g1_signal() {
    cleanup_isaac_g1 "$pidfile"
    if [ -n "$exec_pid" ]; then
      kill "$exec_pid" 2>/dev/null || true
      wait "$exec_pid" 2>/dev/null || true
    fi
    exit 143
  }
  trap on_isaac_g1_signal INT TERM HUP
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  # The Docker exec transport can report 1 when Kit needs the bounded os._exit
  # teardown, even though the process and the in-container wait both return 0.
  # The short-lived wrapper therefore records the authoritative child status.
  docker exec -e DISPLAY="$DISPLAY" "${LIVESTREAM_ENV[@]}" "$container_id" bash -lc '
    source /opt/humanoid-lab/entrypoint.sh
    use-isaac-sonic
    # Avoid treating every repository or /tmp entry as a Kit extension.
    mkdir -p /tmp/humanoid-lab-kit-cwd
    cd /tmp/humanoid-lab-kit-cwd
    pidfile=$1
    statusfile=$2
    profile_file=$3
    shift 3
    exec 9>/tmp/humanoid-lab-isaac-g1.lock
    if ! flock -n 9; then
      echo "error: another Isaac G1 simulation is already running" >&2
      exit 3
    fi
    rm -f -- "$pidfile"
    rm -f -- "$statusfile"
    setsid python /workspace/humanoid-lab/scripts/run-isaac-g1.py \
      --profile "/workspace/humanoid-lab/$profile_file" "$@" &
    isaac_pid=$!
    printf "%s\n" "$isaac_pid" >"$pidfile"
    cleanup_runner() {
      kill -- "-$isaac_pid" 2>/dev/null || kill "$isaac_pid" 2>/dev/null || true
      rm -f -- "$pidfile" "$statusfile"
    }
    trap "cleanup_runner; exit 143" INT TERM HUP
    if wait "$isaac_pid"; then rc=0; else rc=$?; fi
    printf "{\"event\":\"isaac_g1_process_exit\",\"exit_code\":%s}\n" "$rc"
    printf "%s\n" "$rc" >"$statusfile"
    trap - INT TERM HUP
    rm -f -- "$pidfile"
    exit "$rc"
  ' -- "$pidfile" "$statusfile" "$profile_file" "$@" &
  exec_pid=$!
  if wait "$exec_pid"; then rc=0; else rc=$?; fi
  recorded_rc="$(docker exec "$container_id" bash -lc 'cat -- "$1" 2>/dev/null' -- "$statusfile" || true)"
  case "$recorded_rc" in
    0|1|2|3|126|127) rc="$recorded_rc" ;;
  esac
  docker exec "$container_id" rm -f -- "$statusfile" >/dev/null 2>&1 || true
  trap - INT TERM HUP
  cleanup_isaac_g1 "$pidfile"
  return "$rc"
}

cleanup_isaac_stream() { # $1 = container-side pidfile
  local pidfile="$1"
  local container_id
  container_id="$(DC ps -q dev 2>/dev/null)" || return 0
  [ -n "$container_id" ] || return 0
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  docker exec "$container_id" bash -lc '
    pidfile=$1
    [ -r "$pidfile" ] || exit 0
    read -r pid <"$pidfile" || exit 0
    case "$pid" in (*[!0-9]*|"") rm -f -- "$pidfile"; exit 0;; esac
    if [ -r "/proc/$pid/cmdline" ] &&
       tr "\0" " " <"/proc/$pid/cmdline" | grep -Fq "isaacsim.exp.full.streaming.kit"; then
      # runheadless.sh starts the app in its own session, so this also stops
      # the Kit children it spawned.
      kill -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
      for _ in {1..20}; do
        [ ! -d "/proc/$pid" ] && break
        sleep 0.1
      done
      [ ! -d "/proc/$pid" ] || kill -KILL -- "-$pid" 2>/dev/null || true
    fi
    rm -f -- "$pidfile"
  ' -- "$pidfile" >/dev/null 2>&1 || true
}

run_isaac_stream() {
  # Full Isaac Sim UI without a local window: runheadless.sh starts the WebRTC
  # streaming experience and serves it for a client to connect to.
  local pidfile="/tmp/humanoid-lab-isaac-stream-$$-$RANDOM.pid"
  local exec_pid=""
  local rc
  local -a kit_args=(--/app/livestream/port="${ISAAC_LIVESTREAM_PORT:-49100}")
  [ -z "$ISAAC_LIVESTREAM_ENDPOINT" ] ||
    kit_args+=(--/app/livestream/publicEndpointAddress="$ISAAC_LIVESTREAM_ENDPOINT")

  on_isaac_stream_signal() {
    cleanup_isaac_stream "$pidfile"
    if [ -n "$exec_pid" ]; then
      kill "$exec_pid" 2>/dev/null || true
      wait "$exec_pid" 2>/dev/null || true
    fi
    exit 143
  }
  trap on_isaac_stream_signal INT TERM HUP
  # shellcheck disable=SC2016 # Variables in this string expand in the container.
  DC exec -T dev bash -lc '
    pidfile=$1
    shift
    cd /isaac-sim
    setsid ./runheadless.sh "$@" &
    stream_pid=$!
    printf "%s\n" "$stream_pid" >"$pidfile"
    cleanup_stream() {
      kill -- "-$stream_pid" 2>/dev/null || kill "$stream_pid" 2>/dev/null || true
      rm -f -- "$pidfile"
    }
    trap "cleanup_stream; exit 143" INT TERM HUP
    if wait "$stream_pid"; then rc=0; else rc=$?; fi
    trap - INT TERM HUP
    rm -f -- "$pidfile"
    exit "$rc"
  ' -- "$pidfile" "${kit_args[@]}" &
  exec_pid=$!
  if wait "$exec_pid"; then rc=0; else rc=$?; fi
  trap - INT TERM HUP
  cleanup_isaac_stream "$pidfile"
  return "$rc"
}

case "${1:-}" in
  "")
    up_once
    DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && exec bash"
    ;;
  isaac)      shell_env use-isaac-sonic ;;
  isaac-demo)
    [ "$#" -ge 2 ] || { echo "usage: $0 isaac-demo <demo.py> [--gui|--headless|--livestream 1|2] [Isaac Lab args]" >&2; exit 2; }
    isaac_demo "$2" "${@:3}"
    ;;
  isaac-stream)
    livestream_settings
    livestream_banner isaac-stream
    up_once
    run_isaac_stream
    ;;
  webrtc-client)
    client_path="${ISAAC_WEBRTC_CLIENT:-$HOME/Applications/IsaacSim/isaacsim-webrtc-streaming-client-1.1.5-linux-x64.AppImage}"
    [ -x "$client_path" ] || {
      echo "error: WebRTC client missing: $client_path" >&2
      echo "run: ./scripts/install-isaac-webrtc-client.sh" >&2
      exit 2
    }
    # The AppImage mounts itself below /tmp, so its Chromium SUID sandbox helper
    # can never be root-owned; the trusted NVIDIA client runs without it.
    exec "$client_path" --no-sandbox "${@:2}"
    ;;
  sonic-sim)  shell_env use-sonic-sim ;;
  groot)      shell_env use-groot ;;
  psi0)       shell_env use-psi0 ;;
  isaac-g1)
    profile="${2:-}"
    case "$profile" in
      no_hands) profile_file=configs/profiles/isaac-g1-no_hands.json ;;
      inspire-ftp) profile_file=configs/profiles/isaac-g1-inspire-ftp.json ;;
      dex3) profile_file=configs/profiles/isaac-g1-dex3.json ;;
      *) echo "usage: $0 isaac-g1 {no_hands|inspire-ftp|dex3} [--test passive-fall] [--head-camera-window] [--duration SECONDS] [--gui|--headless]" >&2; exit 2 ;;
    esac
    g1_mode_args isaac-g1 "${@:3}"
    up_once
    run_isaac_g1 "$profile_file" "${G1_ARGS[@]}" "${@:3}"
    ;;
  isaac-g1-test-controller)
    [ "${2:-}" = "dex3" ] || { echo "usage: $0 isaac-g1-test-controller dex3 [--head-camera-window] [--duration SECONDS] [--gui|--headless]" >&2; exit 2; }
    g1_mode_args isaac-g1-test-controller "${@:3}"
    up_once
    run_isaac_g1 configs/profiles/isaac-g1-scripted-hold-dex3.json \
      --test controlled-hold "${G1_ARGS[@]}" "${@:3}"
    ;;
  isaac-g1-direct-reference)
    [ "${2:-}" = "dex3" ] || { echo "usage: $0 isaac-g1-direct-reference dex3 --trajectory-reference PATH [--duration SECONDS] [--record-video PATH] [--gui|--headless]" >&2; exit 2; }
    g1_mode_args isaac-g1-direct-reference "${@:3}"
    up_once
    run_isaac_g1 configs/profiles/isaac-g1-direct-reference-dex3.json "${G1_ARGS[@]}" "${@:3}"
    ;;
  isaac-g1-sonic-fixed-base)
    [ "${2:-}" = "dex3" ] || { echo "usage: $0 isaac-g1-sonic-fixed-base dex3 [--duration SECONDS] [--gui|--headless]" >&2; exit 2; }
    g1_mode_args isaac-g1-sonic-fixed-base "${@:3}"
    up_once
    run_isaac_g1 configs/profiles/isaac-g1-sonic-fixed-base-dex3.json "${G1_ARGS[@]}" "${@:3}"
    ;;
  isaac-g1-kinematic)
    # Frame-exact replay: no controller, no PD, no support band; every frame is
    # written straight into the simulation with write_joint_state_to_sim.
    [ "${2:-}" = "dex3" ] || { echo "usage: $0 isaac-g1-kinematic dex3 --kinematic-reference PATH [--kinematic-label LABEL] [--record-video PATH] [--tracking-output PATH] [--metrics-output PATH] [--gui|--headless]" >&2; exit 2; }
    g1_mode_args isaac-g1-kinematic "${@:3}"
    up_once
    run_isaac_g1 configs/profiles/isaac-g1-kinematic-dex3.json "${G1_ARGS[@]}" "${@:3}"
    ;;
  isaac-g1-sonic)
    profile="${2:-}"
    case "$profile" in
      dex3) profile_file=configs/profiles/isaac-g1-sonic-dex3.json ;;
      inspire-ftp) profile_file=configs/profiles/isaac-g1-sonic-inspire-ftp.json ;;
      *) echo "usage: $0 isaac-g1-sonic {dex3|inspire-ftp} [--head-camera-window] [--duration SECONDS] [--record-video PATH] [--controller none] [--gui|--headless]" >&2; exit 2 ;;
    esac
    g1_mode_args isaac-g1-sonic "${@:3}"
    up_once
    run_isaac_g1 "$profile_file" "${G1_ARGS[@]}" "${@:3}"
    ;;
  sonic-controller)
    # The official SONIC deployment in this terminal, exactly as the upstream
    # documentation runs it: raw keyboard on this TTY, planner loaded, `]` to
    # start. This launcher owns the Isaac-targeted controller role: a new
    # invocation replaces an older controller started through this same path,
    # without touching unmarked SONIC/MuJoCo deployments.
    # The deployment owns this terminal's stdin; every variable below expands
    # inside the container.
    up_once
    # shellcheck disable=SC2016
    sonic_input_type="${2:-keyboard}"
    case "$sonic_input_type" in keyboard|zmq_manager) ;; *) echo "usage: $0 sonic-controller [keyboard|zmq_manager]" >&2; exit 2;; esac
    DC exec dev bash -lc '
      source /opt/humanoid-lab/entrypoint.sh
      cd /data/models/sonic-deploy
      export LD_LIBRARY_PATH=/data/models/sonic-deploy/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      export SONIC_MODELS_DIR=/data/models/sonic
      export SONIC_REFERENCE_DIR=/data/models/sonic-isaac/reference/example
      export SONIC_PLANNER=/data/models/sonic-isaac/planner/target_vel/V2/planner_sonic.onnx
      case "$SONIC_PLANNER" in
        *V0*|*V1*|*V2*) ;;
        *) echo "error: the deployment reads its planner version token from the path;" >&2
           echo "       planner version token (V0/V1/V2) missing in: $SONIC_PLANNER" >&2
           exit 2 ;;
      esac
      controller_pidfile=/tmp/humanoid-lab-sonic-controller-isaac.pid
      takeover_lock=/tmp/humanoid-lab-sonic-controller-isaac.takeover.lock
      controller_target=isaac

      is_isaac_controller() {
        candidate=$1
        case "$candidate" in (*[!0-9]*|"") return 1;; esac
        [ -r "/proc/$candidate/environ" ] || return 1
        [ -r "/proc/$candidate/cmdline" ] || return 1
        tr "\0" "\n" <"/proc/$candidate/environ" |
          grep -Fxq "HUMANOID_LAB_CONTROLLER_TARGET=$controller_target" || return 1
        tr "\0" " " <"/proc/$candidate/cmdline" |
          grep -Fq "g1_deploy_onnx_ref" || return 1
      }

      # Serialize only the short replacement transaction. The lock is released
      # before exec so a later invocation can enter, stop this PID, and take over.
      exec 8>"$takeover_lock"
      flock 8
      if [ -r "$controller_pidfile" ]; then
        read -r previous_pid <"$controller_pidfile" || previous_pid=
        if is_isaac_controller "$previous_pid" && [ "$previous_pid" != "$$" ]; then
          echo "[sonic-controller] replacing previous Isaac controller pid=$previous_pid" >&2
          kill -TERM "$previous_pid" 2>/dev/null || true
          for _ in {1..50}; do
            [ ! -d "/proc/$previous_pid" ] && break
            sleep 0.1
          done
          [ ! -d "/proc/$previous_pid" ] || kill -KILL "$previous_pid" 2>/dev/null || true
        fi
      fi
      export HUMANOID_LAB_CONTROLLER_TARGET="$controller_target"
      printf "%s\n" "$$" >"$controller_pidfile"
      flock -u 8
      exec 8>&-
      exec ./g1_deploy_onnx_ref lo \
        "$SONIC_MODELS_DIR/sonic_v1_1/model_decoder.onnx" \
        "$SONIC_REFERENCE_DIR" \
        --obs-config "$SONIC_MODELS_DIR/sonic_v1_1/observation_config.yaml" \
        --encoder-file "$SONIC_MODELS_DIR/sonic_v1_1/model_encoder.onnx" \
        --planner-file "$SONIC_PLANNER" \
        --input-type "$1" --output-type zmq --disable-crc-check' sonic-controller "$sonic_input_type"
    ;;
  doctor)
    ./doctor.sh
    ;;
  smoke)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && /opt/humanoid-lab/smoke-test.sh'
    ;;
  groot-finetune-smoke)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-groot && exec /opt/humanoid-lab/groot-finetune-smoke.sh "$@"' groot-finetune-smoke "${@:2}"
    ;;
  psi0-smoke)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-psi0 && exec /opt/humanoid-lab/psi0-env-smoke.sh "$@"' psi0-smoke "${@:2}"
    ;;
  sonic-dataset-validate)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/validate-sonic-dataset.py "$@"' sonic-dataset-validate "${@:2}"
    ;;
  sonic-pilot)
    # One user-facing build command: source mapping/QC runs in isaac-sonic and
    # launches the sole production encoder path in the pinned sonic-sim venv.
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/prepare-sonic-pilot.py "$@"' sonic-pilot "${@:2}"
    ;;
  sonic-encode)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-sonic-sim && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/encode-sonic-episode.py "$@"' sonic-encode "${@:2}"
    ;;
  sonic-review)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/build-sonic-pilot-review.py "$@"' sonic-review "${@:2}"
    ;;
  sonic-review-serve)
    # Stays on the host: the reviewing browser runs here, so a port published
    # from inside the container would not be reachable.  HUMANOID_DATA_ROOT is
    # the host path of the container's /data.  Unlike `python3 -m http.server`
    # this answers byte ranges, which is what makes the review videos seekable.
    exec python3 scripts/serve-sonic-review.py \
      --directory "$HUMANOID_DATA_ROOT/datasets/first_tur_processed" "${@:2}"
    ;;
  sonic-unitree-qc-serve)
    exec python3 scripts/serve-sonic-review.py \
      --directory "$HUMANOID_DATA_ROOT/datasets" "${@:2}"
    ;;
  sonic-convert)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/convert-sonic-dataset.py "$@"' sonic-convert "${@:2}"
    ;;
  sonic-convert-unitree)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && PYTHONPATH=src exec python3 scripts/convert-unitree-sonic-production.py "$@"' sonic-convert-unitree "${@:2}"
    ;;
  sonic-convert-unitree-summary)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && exec python3 scripts/summarize-unitree-sonic-production.py "$@"' sonic-convert-unitree-summary "${@:2}"
    ;;
  sonic-tests)
    # Unit tests run in the conversion environment; the ONNX encoder tests need
    # onnxruntime, which only the simulation environment pins.
    up_once
    DC exec -T dev bash -lc '
      source /opt/humanoid-lab/entrypoint.sh
      cd /workspace/humanoid-lab
      set -e
      use-isaac-sonic
      PYTHONPATH=src python3 -m pytest tests -q
      use-sonic-sim
      PYTHONPATH=src python3 -m unittest discover -s tests -p "test_sonic_encoder_runner.py" -v' sonic-tests "${@:2}"
    ;;
  sonic-verify)
    # Independent arithmetic check of a converted Unitree episode: re-derives the
    # canonical reference from the raw parquet without importing the pipeline and
    # compares it against the stored artifacts (joint mapping, resampling,
    # velocities, limits, hand order, the 1751D observation, the 78D action).
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && cd /workspace/humanoid-lab && exec python3 scripts/verify-sonic-unitree-conversion.py "$@"' sonic-verify "${@:2}"
    ;;
  fetch-psi0-ckpt)
    up_once
    # Same HF CLI and lock-reading python as fetch-models; the psi0 environment
    # is not needed for the download itself.
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && exec /workspace/humanoid-lab/scripts/fetch-psi0-checkpoint.sh "$@"' fetch-psi0-ckpt "${@:2}"
    ;;
  sync)
    up_once
    DC exec -T dev /opt/humanoid-lab/bootstrap-venvs.sh
    ;;
  fetch-models)
    up_once
    DC exec dev bash -lc "source /opt/humanoid-lab/entrypoint.sh && use-isaac-sonic && scripts/fetch-models.sh"
    ;;
  fetch-groot-demo-data)
    up_once
    DC exec -T dev bash -lc 'source /opt/humanoid-lab/entrypoint.sh && use-groot && exec /opt/humanoid-lab/fetch-groot-demo-data.sh "$@"' fetch-groot-demo-data "${@:2}"
    ;;
  hf-login)
    up_once
    DC exec dev bash -lc '
      source /opt/humanoid-lab/entrypoint.sh && use-groot
      if hf auth login --help >/dev/null 2>&1; then exec hf auth login; fi
      if hf login --help >/dev/null 2>&1; then exec hf login; fi
      exec huggingface-cli login'
    ;;
  stop)
    DC stop
    ;;
  rebuild)
    docker compose --env-file .env --progress=plain build dev
    DC up -d --force-recreate dev
    ;;
  foxy)
    echo "error: foxy profile not enabled" >&2
    exit 2
    ;;
  *)
    echo "usage: $0 [isaac|isaac-demo|isaac-stream|webrtc-client|sonic-sim|groot|psi0|isaac-g1 {no_hands|inspire-ftp|dex3}|isaac-g1-test-controller dex3|isaac-g1-direct-reference dex3|isaac-g1-sonic-fixed-base dex3|isaac-g1-sonic {dex3|inspire-ftp}|sonic-controller|sonic-dataset-validate|sonic-pilot|sonic-encode|sonic-review|sonic-review-serve|sonic-convert|sonic-convert-unitree|sonic-tests|sonic-verify|doctor|smoke|groot-finetune-smoke|psi0-smoke|sync|fetch-models|fetch-psi0-ckpt|fetch-groot-demo-data|hf-login|stop|rebuild|foxy]" >&2
    exit 2
    ;;
esac
