#!/usr/bin/env python3
"""render-lock-env.py — versions.lock.yaml -> .generated/versions.env.

Single source of truth: Compose/Dockerfile/setup.sh read values from this render.
Outputs (not committed): versions.env, versions.json, verify-report.txt.
Usage: python3 scripts/render-lock-env.py [--root DIR]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCHEMA = 1


def fail(msg: str) -> None:
    print(f"render-lock-env: error: {msg}", file=sys.stderr)
    sys.exit(2)


def load_lock(path: Path) -> dict:
    try:
        import yaml  # noqa: PLC0415
    except ImportError:
        fail("PyYAML required (python3 -m pip install pyyaml)")
    try:
        data = yaml.safe_load(path.read_text())
    except Exception as exc:  # noqa: BLE001
        fail(f"cannot read {path}: {exc}")
    if not isinstance(data, dict) or data.get("schema") != SCHEMA:
        fail(f"{path}: expected schema {SCHEMA} (got {data.get('schema')!r})")
    return data


def collect_required_false(data: dict, prefix: str = "") -> list[str]:
    """Collect required:false (to-be-verified-on-machine) fields."""
    out: list[str] = []
    for key, val in data.items():
        here = f"{prefix}.{key}" if prefix else key
        if isinstance(val, dict):
            if val.get("required") is False and "value" in val:
                out.append(here)
            out += collect_required_false(val, here)
        elif isinstance(val, list):
            for i, item in enumerate(val):
                if isinstance(item, dict):
                    out += collect_required_false(item, f"{here}[{i}]")
        elif key == "required" and val is False:
            out.append(prefix)
    return sorted(set(out))


def flatten(data: dict, prefix: str = "") -> dict:
    """Flatten value/required dicts: {'value': X, 'required': bool} -> X."""
    out: dict = {}
    for key, val in data.items():
        here = f"{prefix}.{key}" if prefix else key
        if isinstance(val, dict):
            if "value" in val:
                out[here] = val["value"]
            elif val.get("required") is False or key == "note":
                continue  # bare required marker / free-text notes
            else:
                out.update(flatten(val, here))
        elif isinstance(val, list):
            for i, item in enumerate(val):
                if isinstance(item, str):
                    out[f"{here}[{i}]"] = item
                elif isinstance(item, dict):
                    out.update(flatten(item, f"{here}[{i}]"))
        elif isinstance(val, (str, int, float, bool)) or val is None:
            out[here] = val
        else:
            out[here] = json.dumps(val)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--out", type=Path, default=None,
                    help="default: <root>/.generated/versions.env")
    args = ap.parse_args()

    root = args.root.resolve()
    lock = root / "versions.lock.yaml"
    if not lock.is_file():
        fail(f"lock not found: {lock}")

    data = load_lock(lock)
    gen_dir = root / ".generated"
    gen_dir.mkdir(exist_ok=True)
    out_env = args.out.resolve() if args.out else gen_dir / "versions.env"

    flat = flatten(data)

    lines = ["# auto-generated by scripts/render-lock-env.py — DO NOT EDIT",
             "# source: versions.lock.yaml (schema %d)" % SCHEMA, ""]
    for key in sorted(flat):
        if key.endswith(".note") or ".note." in key:
            continue
        val = flat[key]
        env_key = key.replace(".", "_").replace("[", "_").replace("]", "").upper()
        lines.append(f"{env_key}={quote(val)}")
    out_env.write_text("\n".join(lines) + "\n")

    pending = collect_required_false(data)
    report = gen_dir / "verify-report.txt"
    report.write_text(
        "# verify-pins.sh input — 'verified-later' fields (required: false)\n"
        + "\n".join(pending or ["(none)"]) + "\n")

    (gen_dir / "versions.json").write_text(
        json.dumps({"schema": SCHEMA, "lock": flat,
                    "required_false": pending}, indent=2) + "\n")

    print(f"rendered: {out_env}")
    print(f"report  : {report}")
    if pending:
        print(f"required-false (to verify): {len(pending)} fields -> {', '.join(pending)}")
    return 0


def quote(val: object) -> str:
    """shell-dotenv safe value: single-quote if it contains spaces/special chars."""
    s = str(val)
    if s and all(c.isalnum() or c in "._/:@+-~=" for c in s):
        return s
    return "'" + s.replace("'", "'\\''") + "'"


if __name__ == "__main__":
    raise SystemExit(main())